services:
  redis:
    image: redis:7
    container_name: redis
    command: > 
      redis-server 
      --default off 
      --user myuser on >mypassword ~* +@all
    ports:
      - "6379:6379" 
      
  categories-service:
    build: .
    container_name: categories-service
    ports:
      - "6001:6001"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: mypassword
