version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  postgres-master:
    image: postgres:16
    container_name: postgres-master
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - master_data:/var/lib/postgresql/data
      - ./postgres/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/master/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf


  postgres-slave:
    image: postgres:16
    container_name: postgres-slave
    depends_on:
      - postgres-master
    ports:
      - "5433:5432"
    volumes:
      - slave_data:/var/lib/postgresql/data
      - ./postgres/slave/setup.sh:/setup.sh
    entrypoint: ["/bin/bash", "/setup.sh"]



  backend:
    build: .
    container_name: backend-api
    ports:
      - "6001:6001"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres-master
      - postgres-slave

volumes:
  master_data:
  slave_data:
