
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  backend:
    build: .
    container_name: backend-api
    ports:
      - "6001:6001"
    env_file:
      - .env
    depends_on:
      pgbouncer:
      - pgbouncer
      - redis
    networks:
      - backend-net

  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    depends_on:
      patroni1:
        condition: service_healthy
      patroni2:
        condition: service_healthy
    ports:
      - "6432:5432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    environment:
      AUTH_TYPE: plain
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 0.0.0.0 -p 5432 -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend-net

  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.12
    container_name: etcd
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --enable-v2=true
    ports:
      - "2379:2379"
    networks:
      - backend-net  # <- เพิ่มบรรทัดนี้


  patroni1:
    image: ghcr.io/zalando/spilo-15:3.2-p1
    container_name: patroni1
    environment:
      PATRONI_PG_HBA: |
        host all all 0.0.0.0/0 md5
        host replication replicator 0.0.0.0/0 md5
      SCOPE: postgres-cluster
      PGVERSION: "15"
      ETCD_HOST: etcd:2379
      SUPERUSER_PASSWORD: postgres
      REPLICATION_PASSWORD: replicatorpass
    volumes:
      - patroni1_data:/home/postgres/pgdata
    ports:
      - "5432:5432"
    networks:             # <-- เพิ่มตรงนี้
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


  patroni2:
    image: ghcr.io/zalando/spilo-15:3.2-p1
    container_name: patroni2
    environment:
      PATRONI_PG_HBA: |
        host all all 0.0.0.0/0 md5
        host replication replicator 0.0.0.0/0 md5
      SCOPE: postgres-cluster
      PGVERSION: "15"
      ETCD_HOST: etcd:2379
      SUPERUSER_PASSWORD: postgres
      REPLICATION_PASSWORD: replicatorpass
    volumes:
      - patroni2_data:/home/postgres/pgdata
    ports:
      - "5433:5432"
    networks:             # <-- เพิ่มตรงนี้
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10


networks:
  backend-net:
    driver: bridge



volumes:
  patroni1_data:
  patroni2_data: